# Generated by Django 5.2 on 2025-05-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameverse', '0002_alter_comment_contents_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentformpost',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tournamentformpost',
            name='game_name',
        ),
        migrations.RemoveField(
            model_name='tournamentformpost',
            name='team_size',
        ),
        migrations.AddField(
            model_name='tournamentformpost',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AddField(
            model_name='tournamentformpost',
            name='num_players_per_team',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tournamentformpost',
            name='title',
            field=models.CharField(default='Untitled Tournament', max_length=255),
        ),
        migrations.AlterField(
            model_name='tournamentformpost',
            name='required_fields',
            field=models.JSONField(),
        ),
    ]
