# Generated by Django 5.2 on 2025-05-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameverse', '0003_remove_tournamentformpost_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentformpost',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
