# Generated by Django 5.2 on 2025-05-07 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameverse', '0004_tournamentformpost_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentformpost',
            old_name='num_players_per_team',
            new_name='number_of_players',
        ),
        migrations.RemoveField(
            model_name='tournamentformpost',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tournamentformpost',
            name='required_fields',
        ),
        migrations.AddField(
            model_name='tournamentformpost',
            name='fields_required',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='tournamentformpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tournamentformpost',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='OrganizerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='organizer_posts/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameverse.tournamentformpost')),
            ],
        ),
    ]
