# Generated by Django 5.2 on 2025-05-07 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameverse', '0007_remove_tournamentformpost_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentregistration',
            old_name='submission_data',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='tournamentregistration',
            old_name='submitted_by',
            new_name='user',
        ),
    ]
