# Generated by Django 5.2 on 2025-05-07 21:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameverse', '0008_rename_submission_data_tournamentregistration_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentformpost',
            old_name='number_of_players',
            new_name='num_players_per_team',
        ),
        migrations.RemoveField(
            model_name='tournamentformpost',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='tournamentformpost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tournamentformpost',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tournamentformpost',
            name='fields_required',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='tournamentformpost',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
