# Generated by Django 5.2 on 2025-05-07 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameverse', '0009_rename_number_of_players_tournamentformpost_num_players_per_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentformpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tournamentformpost',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tournamentformpost',
            name='fields_required',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='tournamentformpost',
            name='num_players_per_team',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tournamentformpost',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournamentregistration_set', to='gameverse.tournamentformpost'),
        ),
    ]
